<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>MdInternals.Gui</AssemblyName>
    <RootNamespace>MdInternals.Gui</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Elisy.MdInternals\Elisy.MdInternals.csproj" />
  </ItemGroup>
</Project>
